### ISSUE TITLE
Theme.css issues

### ISSUE THREAD

**Issue by phetish** [Victologo/elegance-theme#2]
Current Theme.css TOC  lists the following:

...

- A2 Note Pane
>- A2.1 Note Titlebar - _**DOES NOT EXIST**_
>>- A2.1.1 Idle Note - _**DOES NOT EXIST**_
>>- A2.1.2 Active Note - _**DOES NOT EXIST**_
>>- A2.1.3 Mobile - _**DOES NOT EXIST**_
>- A2.2 Metadata Container   - _**DOES NOT EXIST**_
>>- A2.2.1 Regular Container - _**DOES NOT EXIST**_
>>- A2.2.2 Codeblock - _**DOES NOT EXIST**_
>- A2.3 Document Search - _**ACTUALLY EXISTS AS 2.1**_
>- A2.4 Empty Note Pane
>- A2.5 Active Line Highlight - _**DOES NOT EXIST**_

...

**Comment by Victologo** [comment]
Thank you. Fixed.
